#!/usr/bin/env -S bash

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2

BRANCH_NAME=$(git symbolic-ref --short HEAD 2>/dev/null)

if [ -z "$COMMIT_SOURCE" ] || [ "$COMMIT_SOURCE" = "message" ]; then
    
    if [ "$BRANCH_NAME" = "main" ] || [ "$BRANCH_NAME" = "master" ]; then
        exit 0
    fi
    
    JIRA_TICKET=$(echo "$BRANCH_NAME" | grep -o -E '[A-Z]+-[0-9]+')
    
    if [ -n "$JIRA_TICKET" ]; then
        PREFIX="[$JIRA_TICKET]"
    else
        PREFIX="[$BRANCH_NAME]"
    fi
    
    if ! grep -q "^$PREFIX" "$COMMIT_MSG_FILE"; then
        TEMP_MSG=$(cat "$COMMIT_MSG_FILE")
        echo "$PREFIX $TEMP_MSG" > "$COMMIT_MSG_FILE"
    fi
fi
